# -*- coding: utf-8 -*-
"""DataFrame_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HEaLNa7PORpagLX4MW5b9z1NYksBC8r

# Install pyspark
"""



!sudo apt update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
#Check this site for the latest download link https://www.apache.org/dyn/closer.lua/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!wget -q https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!tar xf spark-3.2.1-bin-hadoop3.2.tgz
!pip install -q findspark
!pip install pyspark
!pip install py4j

import os
import sys
# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop3.2"


import findspark
findspark.init()
findspark.find()

import pyspark

from pyspark.sql import DataFrame, SparkSession
from typing import List
import pyspark.sql.types as T
import pyspark.sql.functions as F

spark= SparkSession \
       .builder \
       .appName("Our First Spark Example") \
       .getOrCreate()

spark

"""# Filtering and sorting

### **1. Introduction to Filtering**

Filtering in PySpark allows us to select rows that meet certain conditions from a DataFrame. You can use either `filter()` or `where()` methods to achieve this.

#### **Syntax for Filtering:**

```python
df.filter(condition)
df.where(condition)
```
- `condition`: A logical expression that is applied to each row of the DataFrame.

#### **Common Filtering Operations:**

1. **Filter Based on a Condition:**
   - Filters rows where a certain condition is true.
   - **Example**: Filter employees where the age is greater than 30.
     ```python
     df.filter(df['age'] > 30).show()
     ```

2. **Filter Using Multiple Conditions:**
   - You can combine multiple conditions using logical operators like `&` (AND), `|` (OR).
   - **Example**: Filter employees where age is greater than 30 and salary is more than 50,000.
     ```python
     df.filter((df['age'] > 30) & (df['salary'] > 50000)).show()
     ```

3. **Filter Using `isin`:**
   - Filters rows where the column value matches any of the provided values.
   - **Example**: Filter employees where the department is either 'HR' or 'IT'.
     ```python
     df.filter(df['department'].isin('HR', 'IT')).show()
     ```

4. **Filter Using `startsWith` or `endsWith`:**
   - Filters rows where the column value starts or ends with a specific string.
   - **Example**: Filter employees whose names start with 'A'.
     ```python
     df.filter(df['name'].startswith('A')).show()
     ```

5. **Filter for Null or Non-Null Values:**
   - Filters rows based on whether a column contains `null` or `not null` values.
   - **Example**: Filter rows where the department is not null.
     ```python
     df.filter(df['department'].isNotNull()).show()
     ```

---

### **2. Introduction to Sorting**

Sorting allows us to order the rows of a DataFrame based on one or more columns. Sorting can be done in ascending or descending order.

#### **Syntax for Sorting:**

```python
df.sort(column_name)
df.orderBy(column_name)
```

#### **Common Sorting Operations:**

1. **Sort by a Single Column (Ascending by Default):**
   - Orders rows based on the values of a single column in ascending order.
   - **Example**: Sort employees by age.
     ```python
     df.orderBy("age").show()
     ```

2. **Sort by a Single Column in Descending Order:**
   - Orders rows based on the values of a single column in descending order.
   - **Example**: Sort employees by age in descending order.
     ```python
     df.orderBy(df['age'].desc()).show()
     ```

3. **Sort by Multiple Columns:**
   - Sorts by one column first and then by another column in case of ties.
   - **Example**: Sort by department (ascending) and salary (descending).
     ```python
     df.orderBy(df['department'].asc(), df['salary'].desc()).show()
     ```

---

### **3. Combining Filtering and Sorting**

You can combine filtering and sorting operations to further refine the results. For example, you can filter rows first and then sort them.

#### **Example**:
Filter employees where age is greater than 30 and salary is more than 40,000, and then sort them by department (ascending) and salary (descending).

```python
df.filter((df['age'] > 30) & (df['salary'] > 40000)).orderBy(df['department'].asc(), df['salary'].desc()).show()
```

---

### **4. Using SQL-Like Queries in PySpark**

PySpark also supports SQL-like syntax for filtering and sorting when you register the DataFrame as a temporary table.

#### **Example**:
First, register the DataFrame as a table, then execute SQL queries:

```python
df.createOrReplaceTempView("employees")

# SQL query to filter and sort
spark.sql("SELECT * FROM employees WHERE age > 30 ORDER BY salary DESC").show()
```

---

### **5. Chaining Operations**

Filtering and sorting operations can be chained to make the code more readable and concise.

#### **Example**:
```python
df.filter(df['age'] > 30).orderBy(df['salary'].desc()).show()
```

---

### **Summary**

- **Filtering** helps in selecting specific rows based on conditions.
- **Sorting** helps in arranging the data based on column values.
- You can combine filtering and sorting to perform advanced data manipulation tasks.
"""

df=spark.read.csv("/content/person_data.csv",header=True)
df.show()

df.filter(df['Age'] > 40).show()

df.filter((df['Age']<40) & (df['First_Name']=='Lucy')).show()

df1=spark.read.csv("/content/employee_data.csv",header=True)
df1.show()

df2=spark.read.json("/content/employee_data.json")
df2.show()



df1.filter(df1['department'].isin('Finance','IT')).show()

df1.filter(df1['name'].endswith('y')).show()

df1.filter(df1['department'].isNotNull()).show()

df1.orderBy("age").show()

df1.orderBy(df1["age"].desc()).show()

df1.orderBy(df1['department'].asc(), df1['salary'].desc()).show()

df1.filter((df1['age'] > 30) & (df1['salary'] > 40000)).orderBy(df1['department'].asc(), df1['salary'].desc()).show()

assignment_data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen", "Ivy", "Jack"],
    "age": [34, 28, 45, 23, 31, 29, 41, 35, 26, 38],
    "salary": [55000, 42000, 70000, 31000, 48000, 46000, 68000, 59000, 39000, 61000],
    "department": ["Sales", "IT", "HR", "IT", "Finance", "Finance", "HR", "Sales", "IT", "HR"]
}

data = list(zip(assignment_data["name"], assignment_data["age"], assignment_data["salary"], assignment_data["department"]))
columns = ["name", "age", "salary", "department"]
df = spark.createDataFrame(data, schema=columns)

df.show()

from pyspark.sql.functions import col

df.filter(df['department'] == 'Finance').orderBy(col("Salary").desc()).limit(3).show()

# Show top 3 highest-paid employees from Finance.

ping the code in the chat

#withcolumnrenamed

df.withColumnRenamed("existing_col_name", "New_col_name").show()

df6=df.withColumnRenamed("name", "first_name")

Lazy evalation

-> a transformation is performed only when action is called for

Pandas -> dataframe

eagar -it perfom the operatoin immadetely

df6.show()