# -*- coding: utf-8 -*-
"""Pyspark_Dataframe_joins

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnUMh-SKSrcPEAK21s6q3sfLT7Jhq4HO
"""



!sudo apt update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
#Check this site for the latest download link https://www.apache.org/dyn/closer.lua/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!wget -q https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
!tar xf spark-3.2.1-bin-hadoop3.2.tgz
!pip install -q findspark
!pip install pyspark
!pip install py4j

import os
import sys
# os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
# os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop3.2"


import findspark
findspark.init()
findspark.find()

import pyspark

from pyspark.sql import DataFrame, SparkSession
from typing import List
import pyspark.sql.types as T
import pyspark.sql.functions as F

spark= SparkSession \
       .builder \
       .appName("Our First Spark Example") \
       .getOrCreate()

spark

"""
---

## 📘 **PySpark Joins – Agenda**

* Introduction to Joins in PySpark
* Inner Join
* Left Outer Join (Left Join)
* Right Outer Join (Right Join)
* Full Outer Join
* Left Semi Join
* Left Anti Join
* Cross Join (Cartesian Product)
* Self Join
* Multiple Column Joins
* Optimize JOins -> big vs Small and Big vs Big table
* Broadcast Joins
* Shuffle Hash Join
* Sort Merge Join
* Bucketing Starategy To load faster
* Handling Null Values in Joins
* Duplicate Column Names After Joins
* Multiple Table Joins (Chaining Joins)
* Conditional Joins (Non-Equi Joins)
* Join Skew Problems and Solutions
* Salting Technique for Skewed Joins
* Adaptive Query Execution (AQE) for Joins
* Join Hints and Strategies
* Window Functions with Joins
* Aggregations with Joins

---

"""

result = df1.join(df2,join_condation,join_type)

df1 -> the left df
df2 -> the right df
join_condation : the column(s) to match
join_tyep : the type of join to perform

# Inner Join

Returns only the rows where thers a match in both tables
Both sides must match, NO match = not in result

customers = spark.createDataFrame([
    (1, "Alice"), (2, "Bob"), (3, "Charlie")
], ["cust_id", "name"])

customers.show()

orders = spark.createDataFrame([
    (101, 1, "Laptop"), (102, 2, "Phone"), (103, 5, "Mouse")
], ["order_id", "cust_id", "product"])

orders.show()

result=orders.join(customers,"cust_id","inner")
result.show()

from ast import Return
Left Outer Join (Left Join)

Returns all rows from the left table and the matched rows from the right table
if there is no match on the right side, null values are used

result=customers.join(orders,"cust_id","left")
result.show()

# Right Outer Join (Right Join)

returns all rows from the right table and the matched rows from the left table
if there is no match on the left side, null values are used

result=customers.join(orders,"cust_id","right")
result.show()

# Full Outer Join

Returns all rows

result=customers.join(orders,"cust_id","full")
result.show()

# Left Semi Join

left semi  join returns all rows from the left table and only
the matched rows from the right table, but it does not include
any data from the right table in the result -> it acts like
a filter
# if you want a unqiue left table rows then we can use left semi join

customers = spark.createDataFrame([
    (1, "Alice"), (2, "Bob")
], ["cust_id", "name"])

orders = spark.createDataFrame([
    (101, 1, "Laptop"), (102, 1, "Mouse"), (103, 2, "Phone")
], ["order_id", "cust_id", "product"])

print("LEFT SEMI JOIN:")
customers.join(orders, "cust_id", "left_semi").show()

customers.join(orders, "cust_id", "left").show()

# Left anti join

Left anti join is the opposite of left semi join.
It returns all rows from the left table where there is no match in the right table.
its the exact opposit of left semi join  ->

it finds whats missing

customers = spark.createDataFrame([
    (1, "Alice"), (2, "Bob"), (3, "Charlie"), (4, "David")
], ["cust_id", "name"])

# Orders DataFrame (RIGHT table - used only for filtering)
orders = spark.createDataFrame([
    (101, 1, "Laptop"), (102, 2, "Phone"), (103, 1, "Mouse")
], ["order_id", "cust_id", "product"])

customers.show()
orders.show()

result = customers.join(orders, "cust_id", "left_anti")
result.show()

result1 = customers.join(orders, "cust_id", "left_semi")
result1.show()

# Cross Join

Returns the Cartesian product of the two DataFrames
#

sizes = spark.createDataFrame([
    ("Small",), ("Medium",), ("Large",)
], ["size"])

colors = spark.createDataFrame([
    ("Red",), ("Blue",)
], ["color"])


sizes.show()
colors.show()

result = sizes.crossJoin(colors)
result.show()

# self JOin

is when you jin a table with itself, you basicllay treat hte samae table as two
seperate tables

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

spark = SparkSession.builder.appName("SelfJoin").getOrCreate()

# Create employees DataFrame
employees = spark.createDataFrame([
    (1, "Alice", None),
    (2, "Bob", 1),
    (3, "Charlie", 1),
    (4, "David", 2)
], ["emp_id", "emp_name", "manager_id"])

# Create aliases
emp = employees.alias("emp")
mgr = employees.alias("mgr")

# Self Join using col() with qualified names
result = emp.join(
    mgr,
    col("emp.manager_id") == col("mgr.emp_id"),
    "left"
).select(
    col("emp.emp_id").alias("employee_id"),
    col("emp.emp_name").alias("employee_name"),
    col("mgr.emp_name").alias("manager_name")
)

result.show()

Multiple Column Joins

when you join tables using more than one column as the
match condations

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("MultiColumnJoin").getOrCreate()

# Sales DataFrame
sales = spark.createDataFrame([
    (1, 101, "Laptop", 5),
    (1, 102, "Mouse", 10),
    (2, 101, "Laptop", 3),
    (2, 103, "Keyboard", 7)
], ["store_id", "product_id", "product_name", "quantity_sold"])

# Inventory DataFrame
inventory = spark.createDataFrame([
    (1, 101, 50),
    (1, 102, 100),
    (2, 101, 30),
    (3, 101, 20)
], ["store_id", "product_id", "stock"])

# Multiple Column Join - Match on BOTH store_id AND product_id
result = sales.join(inventory, ["store_id", "product_id"], "inner")
result.show()