# Regular Expressions

## Table of Contents
1. [What are Regular Expressions?](#what-are-regular-expressions)
2. [Basic Syntax and Patterns](#basic-syntax-and-patterns)
3. [Character Classes](#character-classes)
4. [Quantifiers](#quantifiers)
5. [Anchors and Boundaries](#anchors-and-boundaries)
6. [Groups and Capturing](#groups-and-capturing)
7. [Practical Examples](#practical-examples)
8. [Exercises](#exercises)
9. [Common Use Cases](#common-use-cases)
10. [Best Practices](#best-practices)

---

## What are Regular Expressions?

Regular expressions (regex or regexp) are powerful patterns used to match, search, and manipulate text. They provide a concise way to describe complex text patterns using special characters and syntax.

**Why use regex?**
- Validate input (emails, phone numbers, passwords)
- Search and replace text
- Extract specific information from text
- Parse log files and data
- Clean and format data

---

## Basic Syntax and Patterns

### Literal Characters
The simplest regex matches exact characters:
```
Pattern: cat
Matches: "cat", "concatenate", "catch"
```

### Special Characters (Metacharacters)
These characters have special meanings in regex:
```
. ^ $ * + ? { } [ ] \ | ( )
```

To match these literally, escape them with backslash:
```
Pattern: \$100
Matches: "$100" (not "a100", "b100", etc.)
```

### The Dot (.) - Any Character
Matches any single character except newline:
```
Pattern: c.t
Matches: "cat", "cut", "c9t", "c@t"
Does not match: "ct", "cart"
```

---

## Character Classes

### Basic Character Classes
```
[abc]     - Matches a, b, or c
[a-z]     - Matches any lowercase letter
[A-Z]     - Matches any uppercase letter
[0-9]     - Matches any digit
[a-zA-Z]  - Matches any letter
```

### Negated Character Classes
```
[^abc]    - Matches anything except a, b, or c
[^0-9]    - Matches anything except digits
```

### Predefined Character Classes
```
\d        - Digit [0-9]
\D        - Non-digit [^0-9]
\w        - Word character [a-zA-Z0-9_]
\W        - Non-word character [^a-zA-Z0-9_]
\s        - Whitespace [ \t\n\r\f]
\S        - Non-whitespace [^ \t\n\r\f]
```

**Examples:**
```
Pattern: \d{3}-\d{3}-\d{4}
Matches: "123-456-7890" (phone number format)

Pattern: \w+@\w+\.\w+
Matches: "user@domain.com" (basic email pattern)
```

---

## Quantifiers

Quantifiers specify how many times a character or group should match:

### Basic Quantifiers
```
*         - 0 or more times
+         - 1 or more times
?         - 0 or 1 time (optional)
{n}       - Exactly n times
{n,}      - n or more times
{n,m}     - Between n and m times
```

**Examples:**
```
Pattern: colou?r
Matches: "color" and "colour"

Pattern: \d{2,4}
Matches: "12", "123", "1234" but not "1" or "12345"

Pattern: a+
Matches: "a", "aa", "aaa", etc. but not empty string

Pattern: a*
Matches: "", "a", "aa", "aaa", etc.
```

### Greedy vs Lazy Quantifiers
```
*         - Greedy: matches as much as possible
*?        - Lazy: matches as little as possible
+         - Greedy
+?        - Lazy
```

**Example:**
```
Text: <div>Hello</div><div>World</div>
Pattern: <div>.*</div>     (Greedy)
Matches: "<div>Hello</div><div>World</div>"

Pattern: <div>.*?</div>    (Lazy)
Matches: "<div>Hello</div>" and "<div>World</div>"
```

---

## Anchors and Boundaries

### Position Anchors
```
^         - Start of string/line
$         - End of string/line
\b        - Word boundary
\B        - Non-word boundary
```

**Examples:**
```
Pattern: ^Hello
Matches: "Hello world" but not "Say Hello"

Pattern: world$
Matches: "Hello world" but not "world peace"

Pattern: \bcat\b
Matches: "cat" in "a cat ran" but not in "concatenate"
```

---

## Groups and Capturing

### Grouping with Parentheses
```
(abc)     - Groups abc together
(a|b)     - Matches a OR b
```

### Capturing Groups
Groups capture matched text for later use:
```
Pattern: (\d{2})/(\d{2})/(\d{4})
Text: "12/25/2023"
Captures: Group 1: "12", Group 2: "25", Group 3: "2023"
```

### Non-Capturing Groups
```
(?:abc)   - Groups without capturing
```

---

## Practical Examples

### Email Validation (Basic)
```
Pattern: [a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}
Matches: "user@example.com", "test.email+tag@domain.co.uk"
```

### Phone Number Extraction
```
Pattern: \(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}
Matches: "(123) 456-7890", "123-456-7890", "123.456.7890"
```

### URL Matching
```
Pattern: https?://[^\s]+
Matches: "http://example.com", "https://www.google.com"
```

### Password Validation
```
Pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$
Requirements: At least 8 chars, 1 lowercase, 1 uppercase, 1 digit, 1 special char
```

---

## Exercises

### Exercise 1: Basic Matching
Match the following patterns:
1. Find all words that start with "cat": ________________
2. Find all 3-digit numbers: ________________
3. Find words ending with "ing": ________________

**Test Strings:**
- "The cat caught a catfish while catching mice"
- "I have 123 apples and 45 oranges, total 168 fruits"
- "Running, jumping, and swimming are fun activities"

### Exercise 2: Character Classes
Write patterns for:
1. Valid hexadecimal colors (e.g., #FF5733, #abc): ________________
2. Words with only vowels: ________________
3. Social Security Numbers (XXX-XX-XXXX): ________________

### Exercise 3: Quantifiers
Create patterns for:
1. Optional "s" at the end of "cat" (cat or cats): ________________
2. At least 2 consecutive digits: ________________
3. Between 3 and 5 lowercase letters: ________________

### Exercise 4: Real-World Applications
Write regex patterns for:
1. IPv4 addresses: ________________
2. Credit card numbers (with optional spaces/dashes): ________________
3. Time in 24-hour format (HH:MM): ________________

### Exercise 5: Advanced Patterns
1. Extract domain names from email addresses: ________________
2. Match balanced parentheses (simple case): ________________
3. Find all words that are palindromes: ________________

---

## Common Use Cases

### Data Validation
```javascript
// Email validation
const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const isValid = emailRegex.test("user@example.com");

// Phone number formatting
const phoneRegex = /(\d{3})(\d{3})(\d{4})/;
const formatted = "1234567890".replace(phoneRegex, "($1) $2-$3");
```

### Text Processing
```python
import re

# Extract all numbers from text
text = "I have 123 apples and 456 oranges"
numbers = re.findall(r'\d+', text)  # ['123', '456']

# Replace multiple spaces with single space
clean_text = re.sub(r'\s+', ' ', "Too    many     spaces")
```

### Log File Analysis
```
# Apache log pattern
Pattern: (\d+\.\d+\.\d+\.\d+) - - \[(.*?)\] "(.*?)" (\d+) (\d+)
Captures: IP, timestamp, request, status code, size
```

---

## Best Practices

### 1. Start Simple
Begin with basic patterns and gradually add complexity.

### 2. Use Online Tools
Test your regex with tools like:
- regex101.com
- regexr.com
- regexpal.com

### 3. Comment Complex Patterns
```python
# Match email addresses with explanation
email_pattern = r'''
    ^                       # Start of string
    [a-zA-Z0-9._%+-]+       # Username part
    @                       # @ symbol
    [a-zA-Z0-9.-]+          # Domain name
    \.                      # Dot
    [a-zA-Z]{2,}           # Top-level domain
    $                       # End of string
'''
```

### 4. Consider Performance
- Use specific character classes instead of `.` when possible
- Use non-capturing groups `(?:...)` when you don't need the capture
- Avoid excessive backtracking with careful quantifier use

### 5. Validate Real-World Data
Test your patterns with actual data, including edge cases and invalid inputs.

---

## Answer Key for Exercises

### Exercise 1:
1. `\bcat\w*` or `cat\w*`
2. `\b\d{3}\b`
3. `\w+ing\b`

### Exercise 2:
1. `#[0-9A-Fa-f]{3,6}`
2. `\b[aeiouAEIOU]+\b`
3. `\d{3}-\d{2}-\d{4}`

### Exercise 3:
1. `cats?`
2. `\d{2,}`
3. `[a-z]{3,5}`

### Exercise 4:
1. `\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b`
2. `\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}`
3. `^([01]?[0-9]|2[0-3]):[0-5][0-9]$`

### Exercise 5:
1. `@([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})` (capture group 1)
2. `\([^()]*\)` (simple case)
3. `\b(\w)(?:\w)*\1\b` (simple palindrome detector)




In [ ]:
import re

# WITHOUT escaping the $ (WRONG)
pattern1 = r'$100'
text = "I have $100 and also a100, b100"
print(re.search(pattern1, text))  # None ($ means "end of string")



None


In [ ]:
# WITH escaping the $ (CORRECT)
pattern2 = r'\$100'
print(re.search(pattern2, text).group())  # "$100" - matches literal "$100"

$100




### 🧠 Concept:

In **regular expressions** (`re` module in Python):

* **`$`** is a **special symbol** that means **“end of the string.”**
* If you want to match a **real dollar sign `$`**, you need to **escape it** using a **backslash `\`** like this: `\$`

---

### 💻 Code Breakdown:

```python
import re

# ❌ WRONG: This pattern does not match literal "$100"
pattern1 = r'$100'
text = "I have $100 and also a100, b100"

# This will NOT match anything because '$' means end of string in regex
print(re.search(pattern1, text))  # Output: None
```

* **Why?** `'$100'` is interpreted as:

  * `$` → end of string
  * `100` → match exactly 100 at the end
* But the text has `$100` in the **middle**, not at the **end**, so it doesn't match.

---

```python
# ✅ CORRECT: Escaping the dollar sign to match it literally
pattern2 = r'\$100'
print(re.search(pattern2, text).group())  # Output: $100
```

* **Why this works:**

  * `\$` → match the actual dollar sign `$`
  * `100` → match the number `100`
* So `\$100` matches the **exact string "\$100"**

---

### ✅ Summary:

| Pattern | Meaning      | Matches? |
| ------- | ------------ | -------- |
| `$100`  | "100 at end" | ❌ No     |
| `\$100` | Exact `$100` | ✅ Yes    |

Let me know if you'd like this as a visual or JPG!


In [ ]:
text = "Hello cat, bat,cot, rat! I have $100. Room number is 1234. Pattern: abab."



In [ ]:
import re



# 1. . (Dot)
print("Dot . :", re.findall(r'c.t', text))  # ['cat']

# 2. ^ (Start of string)
print("^ Start :", re.findall(r'^Hello', text))  # ['Hello']

# 3. $ (End of string)
print("$ End :", re.findall(r'abab\.$', text))  # ['abab.']

# 4. * (Zero or more)
print("* Zero or More :", re.findall(r'ab*', text))  # ['a', 'ab', 'a', 'ab', 'ab']

# 5. + (One or more)
print("+ One or More :", re.findall(r'ab+', text))  # ['ab', 'ab', 'ab']

# 6. ? (Zero or One)
print("? Zero or One :", re.findall(r'ab?', text))  # ['a', 'ab', 'a', 'ab', 'ab']

# 7. {} (Exact or range)
print("{} Repetitions :", re.findall(r'\d{2,4}', text))  # ['100', '1234']

# 8. [] (Character set)
print("[] Character Class :", re.findall(r'[cb]at', text))  # ['cat', 'bat']

# 9. \ (Escape / Special)
print("\\ Escape / Special :", re.findall(r'\$[0-9]+', text))  # ['$100']

# 10. | (OR)
print("| OR :", re.findall(r'cat|rat', text))  # ['cat', 'rat']

# 11. () (Grouping)
print("() Grouping :", re.findall(r'(ab)+', text))  # ['ab']


Dot . : ['cat', 'cot']
^ Start : ['Hello']
$ End : ['abab.']
* Zero or More : ['a', 'a', 'a', 'a', 'a', 'ab', 'ab']
+ One or More : ['ab', 'ab']
? Zero or One : ['a', 'a', 'a', 'a', 'a', 'ab', 'ab']
{} Repetitions : ['100', '1234']
[] Character Class : ['cat', 'bat']
\ Escape / Special : ['$100']
| OR : ['cat', 'rat']
() Grouping : ['ab']





```python
text = "Hello cat, bat, rat! I have $100. Room number is 1234. Pattern: abab."
```

---

### ✅ 1. `.` (Dot – any character except newline)

```python
re.findall(r'c.t', text)  # ['cat']
```

* `c.t` matches any character between `c` and `t`
* Matches: **"cat"**, not "cut" or "cot" (they aren’t in the text)

---

### ✅ 2. `^` (Caret – start of the string)

```python
re.findall(r'^Hello', text)  # ['Hello']
```

* `^Hello` matches "Hello" **only if it’s at the beginning** of the string
* Result: ✅ Yes, because text starts with "Hello"

---

### ✅ 3. `$` (Dollar – end of the string)

```python
re.findall(r'abab\.$', text)  # ['abab.']
```

* `abab\.$` matches if the string **ends with "abab."**
* Result: ✅ Yes, this is the **last word in the string**

---

### ✅ 4. `*` (Asterisk – zero or more of previous character)

```python
re.findall(r'ab*', text)  # ['a', 'ab', 'a', 'ab', 'ab']
```

* `b*` matches **0 or more b’s** after `a`
* Matches include:

  * `a` (with 0 `b`s)
  * `ab` (with 1 `b`)
* So it grabs all possible a's with or without trailing b's

---

### ✅ 5. `+` (Plus – one or more of previous character)

```python
re.findall(r'ab+', text)  # ['ab', 'ab', 'ab']
```

* `b+` means **at least one `b`** after `a`
* So only matches `ab`, not plain `a`

---

### ✅ 6. `?` (Question Mark – zero or one of previous character)

```python
re.findall(r'ab?', text)  # ['a', 'ab', 'a', 'ab', 'ab']
```

* `b?` means **optional b**
* Matches:

  * Just `a`
  * Or `ab`
* So you get a mix of both

---

### ✅ 7. `{}` (Braces – specific number of repetitions)

```python
re.findall(r'\d{2,4}', text)  # ['100', '1234']
```

* `\d{2,4}` means find a number with **2 to 4 digits**
* Matches:

  * `100` (3 digits)
  * `1234` (4 digits)

---

### ✅ 8. `[]` (Square brackets – match one of the characters inside)

```python
re.findall(r'[cb]at', text)  # ['cat', 'bat']
```

* `[cb]` means "c OR b"
* Matches:

  * `cat`
  * `bat`
* Doesn’t match `rat` because `r` isn't in the list

---

### ✅ 9. `\` (Backslash – escape special characters)

```python
re.findall(r'\$[0-9]+', text)  # ['$100']
```

* `\$` escapes `$` to match it literally
* `[0-9]+` means one or more digits after `$`
* Matches the amount: `$100`

---

### ✅ 10. `|` (Pipe – OR)

```python
re.findall(r'cat|rat', text)  # ['cat', 'rat']
```

* `cat|rat` matches either "cat" or "rat"
* Both are present in the string, so both are matched

---

### ✅ 11. `()` (Parentheses – grouping)

```python
re.findall(r'(ab)+', text)  # ['ab']
```

* `(ab)+` means one or more repetitions of **"ab"**
* It finds the group `"ab"` repeated in `"abab"` (but returns only last full match due to how `findall` works with groups)




import re

text = "aa ab a abc abbb abbbc aaaa"

print("Original Text:\n", text)
print("\n--- Quantifier Examples ---\n")

# *  (0 or more times)
print("1. '*' => Matches 'ab*' (a followed by 0 or more b's):")
matches = re.findall(r'ab*', text)
print("Matches:", matches)

# +  (1 or more times)
print("\n2. '+' => Matches 'ab+' (a followed by 1 or more b's):")
matches = re.findall(r'ab+', text)
print("Matches:", matches)

# ?  (0 or 1 time)
print("\n3. '?' => Matches 'ab?' (a followed by 0 or 1 b):")
matches = re.findall(r'ab?', text)
print("Matches:", matches)

# {n}  (Exactly n times)
print("\n4. '{3}' => Matches 'ab{3}' (a followed by exactly 3 b's):")
matches = re.findall(r'ab{3}', text)
print("Matches:", matches)

# {n,} (n or more times)
print("\n5. '{2,}' => Matches 'ab{2,}' (a followed by 2 or more b's):")
matches = re.findall(r'ab{2,}', text)
print("Matches:", matches)

# {n,m} (Between n and m times)
print("\n6. '{2,3}' => Matches 'ab{2,3}' (a followed by 2 to 3 b's):")
matches = re.findall(r'ab{2,3}', text)
print("Matches:", matches)


Section 1: Basic Matching

Exact Word Match: Find if the word "Apple" exists in the string.
Case-Insensitive Match: Find if the word "python" (case-insensitive) exists in the string.
Start of String: Check if the very first content (after initial newlines) starts with "Hello".
End of String: Check if the string (after stripping leading/trailing newlines) ends with "75.".
Any Single Character: Find all occurrences of "ma.t" (where '.' can be any single character).
Section 2: Character Sets and Quantifiers

Specific Characters: Find all occurrences of "Pyth" followed by any single character, then 'n' (case-insensitive).
Digits Only: Extract all sequences of one or more digits from the string.
Letters Only: Extract all sequences of one or more letters (alphabetic characters) from the string.
Whitespace: Find all occurrences of one or more whitespace characters.
Zero or One Occurrence: Find "colou?r" to match both "color" and "colour".
Zero or More Occurrences: Find "ab*c" to match "ac", "abc", "abbc", etc.
One or More Occurrences: Find "go+gle" to match "gogle", "google", "gooogle", etc.
Exact Number of Occurrences: Find "a{3}b" to match "aaab".
Range of Occurrences: Find "a{2,4}b" to match "aab", "aaab", "aaaab".
Section 3: Special Sequences and Groups

Word Boundaries: Find the exact word "The" without matching "There" or "Another".
Non-Digit Characters: Find all non-digit characters.
Non-Whitespace Characters: Find all non-whitespace characters.
Capturing Groups (General): From the line "GET /api/users/profile HTTP/1.1" 200 1524, extract the HTTP method ("GET"), the path ("/api/users/profile"), and the status code ("200").
Non-Capturing Groups: Match occurrences of "Python" or "PyThOn" without specifically capturing which one it was, just the whole match.
Alternation (OR): Find either "cat" or "dog" in the string.
Section 4: Advanced Concepts

Replacing Matches: Replace all occurrences of "fun." with "exciting!"
Splitting Strings: Split the string by one or more newline characters.
Matching at the Start of Each Line: Find lines that start with "ERROR:" (case-insensitive) in the multi-line string.
Matching at the End of Each Line: Find lines that end with a number followed by a period (.) in the multi-line string.
Lookahead Assertion (Positive): Find words that are immediately followed by "ing," (e.g., "learn" in "learning," if it were in the string). Self-correction: Will adapt to "sing" in "singing" if present, or provide a similar example. Let's use playing to extract play.
Section 5: Specific Log-Related Extraction & Validation (Pre-Project Warm-up)

Extracting IP Addresses: From the entire ultimate_log_string, extract all valid IPv4 addresses.
Parsing Timestamps: From a log fragment like [21/Jun/2025:10:23:45 +0000], extract the date part (21/Jun/2025), time part (10:23:45), and timezone offset (+0000) separately.
Extracting HTTP Methods: From a log entry, extract only the HTTP method (GET, POST, PUT, DELETE). Apply this to the first log line.
Extracting Request Paths: From a log entry, extract only the request path (e.g., /api/users/profile). Apply this to the first log line.
Extracting Status Codes: From a log entry, extract only the status code (e.g., 200). Apply this to the first log line.
Extracting User Agents and Type: From the User-Agent strings, extract the main browser/client name (e.g., "Chrome", "curl", "Safari", "Googlebot") and identify if it's a 'Mobile', 'Desktop', or 'Bot' user agent.
Validating IP Addresses (Strict): Check if "192.168.1.1" is a valid IPv4, and if "256.0.0.1" is valid.
Identifying Error Messages: Find and extract the full error message (the text after "ERROR:") from the log string.
Identifying Security Alerts: Find and extract the full security alert message (the text after "SECURITY_ALERT:") from the log string.
Extracting Key-Value Pairs from URL Parameters: From the /api/products?category=electronics&price_min=100&sort=asc path, extract all key-value pairs into a dictionary.


In [ ]:
import re
from datetime import datetime
from collections import Counter # For future use in project

ultimate_log_string = """
# SERVER LOG SAMPLE - 2025-06-21
192.168.1.15 - - [21/Jun/2025:10:23:45 +0000] "GET /api/users/profile HTTP/1.1" 200 1524 "https://techstart.com/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
10.0.0.25 - admin [21/Jun/2025:10:24:12 +0000] "POST /api/auth/login HTTP/1.1" 401 0 "-" "curl/7.68.0"
203.0.113.45 - - [21/Jun/2025:10:25:33 +0000] "GET /static/images/logo.png HTTP/1.1" 200 15234 "https://techstart.com/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1"
192.168.1.100 - user123 [21/Jun/2025:10:26:01 +0000] "DELETE /api/users/456 HTTP/1.1" 204 0 "https://techstart.com/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
ERROR: Invalid request from 192.168.1.200 at [21/Jun/2025:10:26:45 +0000] - malformed JSON payload.
10.0.0.33 - - [21/Jun/2025:10:27:12 +0000] "GET /api/products?category=electronics&price_min=100&sort=asc HTTP/1.1" 200 8945 "https://google.com" "Mozilla/5.0 (Linux; Android 11; Pixel 4a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36"
SECURITY_ALERT: Potential SQL injection attempt from 203.0.113.99 at [21/Jun/2025:10:28:00 +0000] in query: "'; DROP TABLE users; --"
192.168.1.75 - - [21/Jun/2025:10:29:15 +0000] "PUT /api/settings/notifications HTTP/1.1" 500 234 "https://techstart.com/settings" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
ANOTHER LINE: This is a sentence.  With   multiple  spaces.
Learning python regex is fun. PyThOn is versatile.
I like the color red. What is your favourite colour?
Let's see abracadabra: ac, abc, abbc, abbbbc.
gogle, google, gooogle.
Exactly: aaab. Range: aab, aaab, aaaab, aaaaab.
The cat sat on the mat. The dog barked. There is another word.
Request from 192.168.1.10 and also 10.0.0.5, but not 256.0.0.1.
Another log line. Item: 75.
"""

In [ ]:
# find if the word "apple exists in the string"

match =re.search(r'Apple',ultimate_log_string )
print(match)

<re.Match object; span=(200, 205), match='Apple'>


In [ ]:
match= re.findall(r'Apple', ultimate_log_string)
print(match)

['Apple', 'Apple', 'Apple', 'Apple']


In [ ]:
# Find if the word "python" (case-insensitive) exists in a string.

match = re.findall(r'python', ultimate_log_string, re.IGNORECASE)
print(match)

['python', 'PyThOn']


In [ ]:
#Check if a string starts with "Hello".

match = re.findall(r'^Hello', ultimate_log_string)
print(match)

[]


In [ ]:
# Check if a string ends with "world".

match = re.findall(r'world$', ultimate_log_string)
print(match)

[]


In [ ]:
# Find all occurrences of "b.t".
match = re.findall(r'b.t', ultimate_log_string)
print(match)

['bot', 'bot', 'but']


In [ ]:
# Find "gr" followed by 'a' or 'e' or 'i', then 'y'. (e.g., "gray", "grey", "griy")

match = re.findall(r'gr[aei]y', ultimate_log_string)
print(match)

[]


In [ ]:
# Extract all sequences of one or more digits.

match = re.findall(r'\d+', ultimate_log_string)
print(match)

['2025', '06', '21', '192', '168', '1', '15', '21', '2025', '10', '23', '45', '0000', '1', '1', '200', '1524', '5', '0', '10', '0', '64', '64', '537', '36', '100', '0', '4896', '127', '537', '36', '10', '0', '0', '25', '21', '2025', '10', '24', '12', '0000', '1', '1', '401', '0', '7', '68', '0', '203', '0', '113', '45', '21', '2025', '10', '25', '33', '0000', '1', '1', '200', '15234', '5', '0', '14', '6', '605', '1', '15', '14', '0', '15', '148', '604', '1', '192', '168', '1', '100', '123', '21', '2025', '10', '26', '01', '0000', '456', '1', '1', '204', '0', '5', '0', '10', '15', '7', '605', '1', '15', '14', '1', '2', '605', '1', '15', '192', '168', '1', '200', '21', '2025', '10', '26', '45', '0000', '10', '0', '0', '33', '21', '2025', '10', '27', '12', '0000', '100', '1', '1', '200', '8945', '5', '0', '11', '4', '537', '36', '100', '0', '4896', '127', '537', '36', '203', '0', '113', '99', '21', '2025', '10', '28', '00', '0000', '192', '168', '1', '75', '21', '2025', '10', '29', '15', 

In [ ]:
 #Extract all sequences of one or more letters.

match = re.findall(r'[a-zA-Z]+', ultimate_log_string)
print(match)

['SERVER', 'LOG', 'SAMPLE', 'Jun', 'GET', 'api', 'users', 'profile', 'HTTP', 'https', 'techstart', 'com', 'dashboard', 'Mozilla', 'Windows', 'NT', 'Win', 'x', 'AppleWebKit', 'KHTML', 'like', 'Gecko', 'Chrome', 'Safari', 'admin', 'Jun', 'POST', 'api', 'auth', 'login', 'HTTP', 'curl', 'Jun', 'GET', 'static', 'images', 'logo', 'png', 'HTTP', 'https', 'techstart', 'com', 'Mozilla', 'iPhone', 'CPU', 'iPhone', 'OS', 'like', 'Mac', 'OS', 'X', 'AppleWebKit', 'KHTML', 'like', 'Gecko', 'Version', 'Mobile', 'E', 'Safari', 'user', 'Jun', 'DELETE', 'api', 'users', 'HTTP', 'https', 'techstart', 'com', 'admin', 'Mozilla', 'Macintosh', 'Intel', 'Mac', 'OS', 'X', 'AppleWebKit', 'KHTML', 'like', 'Gecko', 'Version', 'Safari', 'ERROR', 'Invalid', 'request', 'from', 'at', 'Jun', 'malformed', 'JSON', 'payload', 'Jun', 'GET', 'api', 'products', 'category', 'electronics', 'price', 'min', 'sort', 'asc', 'HTTP', 'https', 'google', 'com', 'Mozilla', 'Linux', 'Android', 'Pixel', 'a', 'AppleWebKit', 'KHTML', 'like

In [ ]:
# Find all occurrences of one or more whitespace characters.
match = re.findall(r'\s+', ultimate_log_string)
print(match)

['\n', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', '  ', '   ', '  ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', ' ', ' ', ' ', ' ', ' ', '\n', '

In [ ]:
#Zero or One Occurrence:** Find "colou?r" to match both "color" and "colour"

match = re.findall(r'colou?r', ultimate_log_string)
print(match)

['color', 'colour']


In [ ]:
# Zero or More Occurrences:** Find "ab*c" to match "ac", "abc", "abbc", etc.
match = re.findall(r'ab*c', ultimate_log_string)
print(match)

['ac', 'ac', 'ac', 'ac', 'ac', 'ac', 'abc', 'abbc', 'abbbbc', 'ac']


In [ ]:
# One or More Occurrences:** Find "go+gle" to match "gogle", "google", "gooogle", etc.

match = re.findall(r'go+gle', ultimate_log_string)
print(match)


['google', 'google', 'gogle', 'google', 'gooogle']


In [ ]:
# Exact Number of Occurrences:** Find "a{3}b" to match "aaab".
match = re.findall(r'a{3}b', ultimate_log_string)
print(match)

['aaab', 'aaab', 'aaab', 'aaab']


In [ ]:
 # Find "a{2,4}b" to match "aab", "aaab", "aaaab".
match = re.findall(r'a{2,4}b', ultimate_log_string)
print(match)

['aaab', 'aab', 'aaab', 'aaaab', 'aaaab']


In [ ]:
# Find the exact word "the" without matching "there" or "other".
match = re.findall(r'\bthe\b', ultimate_log_string)
print(match)

['the', 'the']


In [ ]:
 #Find all non-digit characters
match = re.findall(r'\D+', ultimate_log_string)
print(match)

['\n# SERVER LOG SAMPLE - ', '-', '-', '\n', '.', '.', '.', ' - - [', '/Jun/', ':', ':', ':', ' +', '] "GET /api/users/profile HTTP/', '.', '" ', ' ', ' "https://techstart.com/dashboard" "Mozilla/', '.', ' (Windows NT ', '.', '; Win', '; x', ') AppleWebKit/', '.', ' (KHTML, like Gecko) Chrome/', '.', '.', '.', ' Safari/', '.', '"\n', '.', '.', '.', ' - admin [', '/Jun/', ':', ':', ':', ' +', '] "POST /api/auth/login HTTP/', '.', '" ', ' ', ' "-" "curl/', '.', '.', '"\n', '.', '.', '.', ' - - [', '/Jun/', ':', ':', ':', ' +', '] "GET /static/images/logo.png HTTP/', '.', '" ', ' ', ' "https://techstart.com/" "Mozilla/', '.', ' (iPhone; CPU iPhone OS ', '_', ' like Mac OS X) AppleWebKit/', '.', '.', ' (KHTML, like Gecko) Version/', '.', ' Mobile/', 'E', ' Safari/', '.', '"\n', '.', '.', '.', ' - user', ' [', '/Jun/', ':', ':', ':', ' +', '] "DELETE /api/users/', ' HTTP/', '.', '" ', ' ', ' "https://techstart.com/admin" "Mozilla/', '.', ' (Macintosh; Intel Mac OS X ', '_', '_', ') AppleWeb

In [ ]:
# Find all non-whitespace characters.
match = re.findall(r'\S+', ultimate_log_string)
print(match)


['#', 'SERVER', 'LOG', 'SAMPLE', '-', '2025-06-21', '192.168.1.15', '-', '-', '[21/Jun/2025:10:23:45', '+0000]', '"GET', '/api/users/profile', 'HTTP/1.1"', '200', '1524', '"https://techstart.com/dashboard"', '"Mozilla/5.0', '(Windows', 'NT', '10.0;', 'Win64;', 'x64)', 'AppleWebKit/537.36', '(KHTML,', 'like', 'Gecko)', 'Chrome/100.0.4896.127', 'Safari/537.36"', '10.0.0.25', '-', 'admin', '[21/Jun/2025:10:24:12', '+0000]', '"POST', '/api/auth/login', 'HTTP/1.1"', '401', '0', '"-"', '"curl/7.68.0"', '203.0.113.45', '-', '-', '[21/Jun/2025:10:25:33', '+0000]', '"GET', '/static/images/logo.png', 'HTTP/1.1"', '200', '15234', '"https://techstart.com/"', '"Mozilla/5.0', '(iPhone;', 'CPU', 'iPhone', 'OS', '14_6', 'like', 'Mac', 'OS', 'X)', 'AppleWebKit/605.1.15', '(KHTML,', 'like', 'Gecko)', 'Version/14.0', 'Mobile/15E148', 'Safari/604.1"', '192.168.1.100', '-', 'user123', '[21/Jun/2025:10:26:01', '+0000]', '"DELETE', '/api/users/456', 'HTTP/1.1"', '204', '0', '"https://techstart.com/admin"', '

In [ ]:
 #Extract the first name and last name from a string like "John Doe".
match = re.search(r'(Apple), an (orange)', ultimate_log_string)

if match:
    print(match.group(1))
    print(match.group(2))
else:
  print("not found")


not found


In [ ]:
#* Find either "cat" or "dog" in a string.

match = re.findall(r'cat|dog', ultimate_log_string)
print(match)


['cat', 'cat', 'cat', 'dog']


In [ ]:
# Replace all occurrences of "bad" with "good".

match = re.sub(r'bad', 'good', ultimate_log_string)
print(match)



# SERVER LOG SAMPLE - 2025-06-21
192.168.1.15 - - [21/Jun/2025:10:23:45 +0000] "GET /api/users/profile HTTP/1.1" 200 1524 "https://techstart.com/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
10.0.0.25 - admin [21/Jun/2025:10:24:12 +0000] "POST /api/auth/login HTTP/1.1" 401 0 "-" "curl/7.68.0"
203.0.113.45 - - [21/Jun/2025:10:25:33 +0000] "GET /static/images/logo.png HTTP/1.1" 200 15234 "https://techstart.com/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1"
192.168.1.100 - user123 [21/Jun/2025:10:26:01 +0000] "DELETE /api/users/456 HTTP/1.1" 204 0 "https://techstart.com/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
ERROR: Invalid request from 192.168.1.200 at [21/Jun/2025:10:26:45 +0000] - malformed JSON payload.
10.0.0.33 - - [21/J

In [ ]:
#Split a string by one or more spaces.

match = re.split(r'\s+', ultimate_log_string)
print(match)


['', '#', 'SERVER', 'LOG', 'SAMPLE', '-', '2025-06-21', '192.168.1.15', '-', '-', '[21/Jun/2025:10:23:45', '+0000]', '"GET', '/api/users/profile', 'HTTP/1.1"', '200', '1524', '"https://techstart.com/dashboard"', '"Mozilla/5.0', '(Windows', 'NT', '10.0;', 'Win64;', 'x64)', 'AppleWebKit/537.36', '(KHTML,', 'like', 'Gecko)', 'Chrome/100.0.4896.127', 'Safari/537.36"', '10.0.0.25', '-', 'admin', '[21/Jun/2025:10:24:12', '+0000]', '"POST', '/api/auth/login', 'HTTP/1.1"', '401', '0', '"-"', '"curl/7.68.0"', '203.0.113.45', '-', '-', '[21/Jun/2025:10:25:33', '+0000]', '"GET', '/static/images/logo.png', 'HTTP/1.1"', '200', '15234', '"https://techstart.com/"', '"Mozilla/5.0', '(iPhone;', 'CPU', 'iPhone', 'OS', '14_6', 'like', 'Mac', 'OS', 'X)', 'AppleWebKit/605.1.15', '(KHTML,', 'like', 'Gecko)', 'Version/14.0', 'Mobile/15E148', 'Safari/604.1"', '192.168.1.100', '-', 'user123', '[21/Jun/2025:10:26:01', '+0000]', '"DELETE', '/api/users/456', 'HTTP/1.1"', '204', '0', '"https://techstart.com/admin"

In [ ]:
# Find lines that start with "Error:" in a multi-line string.

match = re.findall(r'^ERROR:', ultimate_log_string, re.MULTILINE)
print(match)


['ERROR:']


In [ ]:
# Find lines that end with a number in a multi-line string.

match = re.findall(r'\d+$', ultimate_log_string, re.MULTILINE)
print(match)


['21']


In [ ]:
#Find words that are followed by "ing"#

match = re.findall(r'\b\w+(?=\bing\b)', ultimate_log_string)
print(match)

[]


In [ ]:
 # Find all non-digit characters

In [ ]:
Project

# Web Server Log Analysis - Regex Case Study

## 🎯 Scenario
The company's web server has been experiencing unusual traffic patterns, and your manager has asked you to analyze the server logs to extract meaningful insights. You need to use Python regex to parse and analyze the log data.

## 📝 Learning Objectives
By completing this project, You  will Learn:
- Apply regex patterns to extract specific data from unstructured text
- Use regex groups to capture and organize data
- Implement data validation using regex
- Clean and process real-world messy data
- Generate analytical reports from extracted data

## 📊 Sample Data
Here's a sample of the web server log file (`server_logs.txt`):

```
192.168.1.15 - - [15/Jun/2024:10:23:45 +0000] "GET /api/users/profile HTTP/1.1" 200 1524 "https://techstart.com/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
10.0.0.25 - admin [15/Jun/2024:10:24:12 +0000] "POST /api/auth/login HTTP/1.1" 401 0 "-" "curl/7.68.0"
203.0.113.45 - - [15/Jun/2024:10:25:33 +0000] "GET /static/images/logo.png HTTP/1.1" 200 15234 "https://techstart.com/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X)"
192.168.1.100 - user123 [15/Jun/2024:10:26:01 +0000] "DELETE /api/users/456 HTTP/1.1" 204 0 "https://techstart.com/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
ERROR: Invalid request from 192.168.1.200 at [15/Jun/2024:10:26:45 +0000] - malformed JSON payload
10.0.0.33 - - [15/Jun/2024:10:27:12 +0000] "GET /api/products?category=electronics&price_min=100 HTTP/1.1" 200 8945 "https://google.com" "Mozilla/5.0 (Linux; Android 11)"
SECURITY_ALERT: Potential SQL injection attempt from 203.0.113.99 at [15/Jun/2024:10:28:00 +0000] in query: "'; DROP TABLE users; --"
192.168.1.75 - - [15/Jun/2024:10:29:15 +0000] "PUT /api/settings/notifications HTTP/1.1" 500 234 "https://techstart.com/settings" "Mozilla/5.0"
```

## 🚀 Tasks

### Task 1: Basic Log Parsing (Easy)
Extract basic information from standard log entries:
- IP addresses
- Timestamps
- HTTP methods (GET, POST, PUT, DELETE)
- Response status codes
- Response sizes

**Expected Output**: A list of dictionaries with extracted data

### Task 2: Advanced Data Extraction (Medium)
From the standard log entries, extract:
- User agents and identify device types (mobile, desktop, bot)
- Referrer URLs and categorize traffic sources
- API endpoints and parameters
- User authentication information

### Task 3: Security Analysis (Medium-Hard)
Identify and extract:
- Error messages and their patterns
- Security alerts and the threatening IP addresses
- Failed authentication attempts (status code 401)
- Unusual request patterns that might indicate attacks

### Task 4: Data Validation & Cleaning (Hard)
Implement regex patterns to:
- Validate IP address formats
- Standardize timestamp formats
- Clean and normalize user agent strings
- Identify and flag suspicious request patterns
- Remove or flag malformed log entries

### Task 5: Analytics Dashboard (Challenge)
Create a summary report that includes:
- Top 5 IP addresses by request count
- Most accessed endpoints
- Error rate analysis
- Security incidents summary
- Traffic source breakdown (direct, search engines, referrals)

## 🛠 Technical Requirements

### Required Python Libraries
```python
import re
import json
from datetime import datetime
from collections import Counter, defaultdict
```

### Starter Code Structure
```python
class LogAnalyzer:
    def __init__(self, log_file_path):
        self.log_file_path = log_file_path
        self.parsed_logs = []
        self.security_incidents = []
    
    def parse_standard_log(self, line):
        # TODO: Implement regex pattern for standard log format
        pass
    
    def extract_ip_addresses(self, text):
        # TODO: Implement IP address regex
        pass
    
    def identify_device_type(self, user_agent):
        # TODO: Use regex to identify mobile/desktop/bot
        pass
    
    def detect_security_threats(self, line):
        # TODO: Implement security pattern detection
        pass
    
    def generate_report(self):
        # TODO: Create analytical summary
        pass
```

## 📚 Regex Patterns to Master
Students should learn and apply these regex concepts:

1. **Character Classes**: `\d`, `\w`, `\s`
2. **Quantifiers**: `+`, `*`, `?`, `{n,m}`
3. **Groups**: `()`, named groups `(?P<name>)`
4. **Anchors**: `^`, `$`
5. **Alternatives**: `|`
6. **Special Sequences**: `\b`, `\A`, `\Z`
7. **Lookahead/Lookbehind**: `(?=)`, `(?<=)`

## 🎯 Expected Deliverables

1. **Python script** (`log_analyzer.py`) with complete implementation
2. **Analysis report** (text file or markdown) with findings
3. **Documentation** explaining regex patterns used
4. **Test cases** demonstrating the solution works with various log formats

## 🏆 Bonus Challenges

1. **Real-time Processing**: Modify the solution to process logs as they're written
2. **Visualization**: Create charts showing traffic patterns over time
3. **Configuration**: Make regex patterns configurable via external file
4. **Performance**: Optimize regex patterns for large log files
5. **Multiple Formats**: Handle different log formats (Apache, Nginx, custom)

## 📖 Assessment Criteria

- **Correctness** (40%): Regex patterns correctly extract required data
- **Code Quality** (25%): Clean, readable, well-documented code
- **Completeness** (20%): All tasks completed with proper error handling
- **Analysis** (15%): Insights and conclusions drawn from the data

## 💡 Tips for Success

1. Start with simple patterns and build complexity gradually
2. Test regex patterns with online tools like regex101.com
3. Use raw strings (`r""`) for regex patterns in Python
4. Comment your regex patterns to explain what they match
5. Handle edge cases and malformed data gracefully
6. Use meaningful variable names for captured groups

## 🔍 Sample Expected Results

After completing the project, students should be able to report:
- "Found 1 security alert and 1 error in the log sample"
- "Mobile traffic accounts for 25% of requests"
- "API endpoints receive 75% of traffic"
- "192.168.1.x subnet is the most active IP range"

